### ISSUE TITLE
CRM Card - Not displaying data in Production - Works correctly on local development and sandbox

### ISSUE THREAD

**Issue by rginsberg549** [HubSpot/hubspot-cli#1010]
## Description and Context
I have successfully built a CRM Card which works on local and sandbox environments but once the project is uploaded to the main account - the CRM Card does not display any information. 

The working CRM card titled "Related Clients" can be found [here](https://app.hubspot.com/contacts/45085551/record/0-2/17415565404).

The CRM Card fetches the loaded Company name, industry, and associated custom objects (Spaces and Properties) using GraphQL.

It then performs multiple GraphQL queries to find related Companies where lifecyclestage=customer and industry matches the loaded companies industry, the loaded companies landlords (from space object), or the loaded companies property (from property object).

The main account pays for Sales Enterprise and to my knowledge is support.

Using `hs --version` the result is 5.1.3

### Steps to reproduce

My process was the following....

Used `hs project dev` to prototype CRM Card

Used `hs project upload` to upload the working code to my sandbox (linked above).

Next I changed my account using `hs accounts use --accounts=prod` and then `hs project upload`

I went and added the card to the tab of the company and then nothing displays as intended.  You can see this [here](https://app.hubspot.com/contacts/21459218/record/0-2/19153304162)

## Expected behavior

My expectation was that what ever code was working / running on my local and sandbox environments should also be working on production / main account.

I have no logs/errors display which might help me troubleshoot as the serverless function isn't calling the API endpoint.

## Screenshots

<img width="1511" alt="Screenshot 2024-02-26 at 7 14 03 PM" src="https://github.com/HubSpot/hubspot-cli/assets/39674638/860a2ccf-4c67-4dc3-81ae-90ad4c0ba6f6">

**Comment by kemmerle** [comment]
Hi @rginsberg549, we were digging into the issue a bit on our end and discovered the following errors in the console:

<img width="838" alt="Screenshot 2024-02-27 at 11 08 08 AM" src="https://github.com/HubSpot/hubspot-cli/assets/25392256/eab60716-5b68-4b15-8e0c-ae956d14f17c">

It seems like there's a JavaScript error being thrown when the serverless function `getCurrentCompany` fails, because a response object is returning as null rather than as an object with a CRM property. 

A good debugging strategy is to open the console in your browser and refreshing the page, so you can see the JS errors being thrown. Hope that helps, let us know!

**Comment by rginsberg549** [comment]
@kemmerle Thank you for looking into this.  I felt like I explored all debugging options before reaching out because when I load a company on the main account and view the console - I do not see these errors you provided.

<img width="1509" alt="Screenshot 2024-02-27 at 11 25 32 AM" src="https://github.com/HubSpot/hubspot-cli/assets/39674638/4487bbf7-1b98-4afb-b683-255655d2d1c5">

What I find most interesting is that when you are viewing the companies, the function is being called but when I load the record, it is not. Notice how the only function calls that failed were from 7:56am which is right around when you commented on this issue. --> https://app.hubspot.com/private-apps/21459218/2960086/logs/crm

<img width="1188" alt="Screenshot 2024-02-27 at 11 33 49 AM" src="https://github.com/HubSpot/hubspot-cli/assets/39674638/9335cff0-206f-47f2-8a69-8f59c0555bb4">

**Comment by rginsberg549** [comment]
@kemmerle - Just wanted to follow up on this and see if you have any other suggestions/recomendations?  Why it works locally and on the sandbox site and then doesn't work in production when loading the same company record makes things a bit challenging.

**Comment by rginsberg549** [comment]
The issue for me not seeing the errors was because I was adding the Extension Card to the default view. Since we also had a custom view, the default view was not displaying for me - the custom view was.  I did not add the CRM card to the custom view causing the function to not be called.

I was able to see the errors you shared and debugged accordingly.

Thank you.
