### ISSUE TITLE
Dead link (404) to hubspot-local-dev-lib repo in README.md

### ISSUE THREAD

**Issue by viktorbrech** [HubSpot/hubspot-cli#1033]
## Description and Context
README.md contains link to https://github.com/HubSpot/hubspot-local-dev-lib , which returns 404 as of right now.

### Steps to reproduce
Click on the following link in the following row of this file (https://github.com/HubSpot/hubspot-cli/blob/master/README.md ):

See the node.js `local-dev-lib` library [README](https://github.com/HubSpot/hubspot-local-dev-lib)

## Expected behavior
It should lead to a public github repo

**Comment by brandenrodgers** [comment]
Thanks for reporting @viktorbrech! We're currently in the process of making the local-dev-lib library public and may have jumped the gun with adding the repo links to it. This should be fixed very soon.

**Comment by brandenrodgers** [comment]
This should be publicly-accessible now
