### ISSUE TITLE
Watcher Stops on Syntax Error v5.2.0

### ISSUE THREAD

**Issue by jonathanbrakeathypeanddexternz** [HubSpot/hubspot-cli#1048]
## Description and Context

If a file is saved and there are no errors it is fine, however if there is an error a somewhat long error report is spat out into the terminal and the watcher stops.

It seams to happen on multi-line logic such as an if or foreach statement. Alternatively making a error on a single line the file will still upload on save rather than show an error,  E.G. setting a variable and not closing the {% properly will still upload...

` {% set will_upload = true % }`

I am using node v20.12.2, npm v9.8.1 and hs v5.2.0 with VSCode v1.88.1  on windows 11.  (a colleague is using hs v4.2.0 and its working as expected)

### Steps to reproduce
With the watcher on save a file with a Hubl syntax error. this will print out a long error in the terminal and stop the watcher.

## Expected behavior
In days past an abridged error would be output to the terminal, but the watcher would not stop, so correcting the issue and saving uploads the file. E.G.

`[ERROR] Uploading file /Users/*/*/*/theme/modules/*/*.module/module.html to theme/modules/*/*.module/module.html failed
[ERROR] internal error
[ERROR] line 118: Syntax error in '{% endfor %}': Mismatched end tag, expected: endif
[ERROR] 'hubdb_table' is required but no default is set`

**Comment by jonathanbrakeathypeanddexternz** [comment]
FYI: I've down graded to v4.2.0 and the watcher works as expected.

**Comment by jsines** [comment]
This should be fixed in the current prerelease version: https://github.com/HubSpot/hubspot-cli/pull/1071

Thank you for reporting!
