### ISSUE TITLE
Changes are not reflected in the browser for UI extension due to CORS errors (hs project dev)

### ISSUE THREAD

**Issue by norbertkeri** [HubSpot/hubspot-cli#1308]
EDIT:

Solved, the problem was on my end. It's ublock origin that is blocking the request for some reason, if I disable ublock origin the requests go through, and the changes are reflected properly.

## Description and Context
My UI extension does not pick up local changes when running `hs project dev`, seemingly caused by a CORS issue.

### Steps to reproduce
* Follow the tutorial at https://developers.hubspot.com/beta-docs/guides/crm/ui-extensions/local-development
* Run `hs project dev`
* Open a page that displays the extension's UI card
* Edit a .jsx file in the project

## Expected behavior
I expected the UI in my browser to reflect the changes I made in the .jsx file. This does not happen, the browser does not display the changes, even after manually refreshing the browser. The documentation mentions that

>The extension will be updated with a Developing locally tag, which indicates that changes to your React files will now be picked up automatically on save without needing to refresh.

This "developing locally" tag is missing from the UI.

Opening the developer toolbar in the browser shows that requests are made to some local URLs that fail due to CORS errors:

http://localhost:8080/servers/ui-extensions-dev-server
http://localhost:5173/extensions

If I run these using curl:

```
curl -v 'http://localhost:8080/servers/ui-extensions-dev-server' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br, zstd' -H 'Origin: https://app.hubspot.com' -H 'DNT: 1' -H 'Sec-GPC: 1' -H 'Connection: keep-alive'
```

Then the response does include CORS headers:

```
* Request completely sent off
< HTTP/1.1 200 OK
< X-Powered-By: Express
< Access-Control-Allow-Origin: *
< Content-Type: application/json; charset=utf-8
< Content-Length: 13
< ETag: W/"d-Gln5SyevFhVw0kFdtVgZHSZncF4"
< Date: Tue, 17 Dec 2024 21:00:38 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
< 
* Connection #0 to host localhost left intact
{"port":5173}                 
```

If I make a change to a local file, it seems the CLI does pick it up:

```
[INFO] Extension Hello Public App updated, compiled
```

## Screenshots
![1734454982](https://github.com/user-attachments/assets/9916f2cd-7eb5-4682-9f17-1b1ff6e7e2dd)

CLI version: 6.4.0

**Comment by norbertkeri** [comment]
Solved, see edit at top.

**Comment by joe-yeager** [comment]
Thanks for opening the issue and sharing your findings @norbertkeri!  This is valuable information.
