### ISSUE TITLE
Bring typescript to the party

### ISSUE THREAD

**Issue by gcorne** [HubSpot/hubspot-cli#161]

**Comment by gcorne** [comment]
I am going to start by trying to wire up typescript compiling and see how it likes our code.

**Comment by neobats** [comment]
Hey there! I was wondering if there was any work on this that I could contribute to. We're using TS and expanding on the cms-react-boilerplate. It would be awesome if I could have part of a `.d.ts` file to work off of as we try to flesh out the typing in our project.

**Comment by TanyaScales** [comment]
Closing this out as future plans for cli-lib do include the use of TypeScript, but as the lib has been migrated to its own repo. This will no longer be tracked here.
