### ISSUE TITLE
InterpretException Invalid choices list

### ISSUE THREAD

**Issue by matiasvad** [HubSpot/hubspot-cli#182]
In version `1.1.2` (and perhaps before) the parser throws an error when using `choice` to create a dropdown list, with comma-separated choices.

Can be replicated by the following chain of commands.
`hs create template test`
`hs watch <src> <dest>`

Add: ` {% choice "type_of_page" label='Choose the type of page', value='About', choices='[[\"value1\", \"Label 1\"], [\"value2\", \"Label 2\"]]' %}`exactly as portrayed in: https://designers.hubspot.com/docs/hubl/tags#choice

And the error occurs: 
```
[ERROR] Error validating template.
[ERROR] line 19: InterpretException: Invalid choices list: [[value1, Label 1], [value2, Label 2]]
```

I've also tested with `templateType: module` and the old (which we currently use) `templateType: "page"`

Doing the same in the Design Manager throws no errors.

**Comment by gcorne** [comment]
@mattcoley do you happen to know if we fixed this on the backend?

**Comment by mattcoley** [comment]
I have an issue up to work on several of these parsing errors.
