### ISSUE TITLE
Improve hs auth error message when no config exists 

### ISSUE THREAD

**Issue by williamspiro** [HubSpot/hubspot-cli#190]
<img width="379" alt="Screen Shot 2020-05-06 at 1 20 23 PM" src="https://user-images.githubusercontent.com/35824747/81207969-66c3ce80-8f9c-11ea-802e-1a7e28c26499.png">

We should update this error to provide instructions on how to proceed to create a config file, through running `hs init`

**Comment by miketalley** [comment]
Fixed in #486
