### ISSUE TITLE
Support filemanager watch

### ISSUE THREAD

**Issue by williamspiro** [HubSpot/hubspot-cli#193]
Related to https://github.com/HubSpot/hubspot-cms-tools/issues/13

This would add `watch` support for the `filemanager` command, where changed, or new files in a watched directory would automatically be uploaded, similar to `watch` for Design Manager projects.

Reporting in https://hubspotdev.slack.com/archives/CLJJXGTC0/p1588808016296500

**Comment by douglaswelcome** [comment]
+1

**Comment by brandenrodgers** [comment]
Closing b/c this not something we are going to do.
