### ISSUE TITLE
Move/rename file command

### ISSUE THREAD

**Issue by williamspiro** [HubSpot/hubspot-cli#223]
With the CLI, a move/rename is actually a new file in the Design Manager, which means the old file lingers, and history about the original file is lost. 

cc @mattcoley @gcorne @miketalley

**Comment by miketalley** [comment]
Reopening this to explore the possibility of modifying the watch command to use the new endpoint so we can retain revision history for the renamed file.

**Comment by miketalley** [comment]
I had been working on a solution that retains the revision history for watched files when renaming/moving [here](https://github.com/HubSpot/hubspot-cms-tools/pull/369), but it seems to me there is not a good way to do this currently based on how node events work. @williamspiro
