### ISSUE TITLE
Add Support for Marketplace Validation

### ISSUE THREAD

**Issue by KatzMitch** [HubSpot/hubspot-cli#227]
When a marketplace provider submits a new listing, we run a series of validations against the listing. https://knowledge.hubspot.com/resources/what-are-the-submission-requirements-for-the-template-marketplace is our full list of requirements, some are still manual checks, and some are run automatically in the backend.

It would be great if we could surface these checks directly to providers so they can validate their submissions before attempting to list them, it should cut down on the feedback loop significantly

cc: @ckconant

**Comment by TanyaScales** [comment]
Theme and module validation have been added via https://github.com/HubSpot/hubspot-cli/pull/449 and https://github.com/HubSpot/hubspot-cli/pull/649 and subsequent improvement PRs - closing this issue out
