### ISSUE TITLE
Idea: Use external repo as `create` option

### ISSUE THREAD

**Issue by matiasvad** [HubSpot/hubspot-cli#250]
Having an option on `hs create` to create a type (could be theme, module, etc), based on an external repository (public as well as private) would unify starting and working in a project - be it from the HubSpot boilerplates or homebrewed.

This would enable us to "package" themes, templates, modules, etc. (perhaps this could even open up to another issue thread, being able to add dependencies in a `.json`, and run an `install` command, which pulls the set of modules/templates, defined..)

Anyways..

It could look like `hs create website-theme --external-git-url --external-git-version`. 
The auth details from Github/Gitlab would live in `hubspot.config.yml`, for private repositories.

I understand that the external repository would need to be set up in a certain way, like the current `cms-theme-boilerplate`, perhaps with a kind of config-file necessary for the CLI to read it correctly.

Our alternative right now is either the old approach:
- Copy our boilerplate to the project, and continue the work with the CLI.

Or creating our own script that pulls the "package(s)" we need into the project.

**Comment by miketalley** [comment]
One thought on this would be to mimic the way that vue-cli works with using templates for init -- you pass the github `UserName/RepoName`. So the result would be...

`hs create HubSpot/cms-theme-boilerplate destinationFolderName`

We would definitely need the config to determine what kind of asset is being created, so maybe a .json file in the root of the project?

An alternative would be to add the types of assets as a subcommand to the `hs create` command and use a command like...

`hs create module HubSpot/cms-vue-module-template`

The benefit of this being that we don't need the .json to identify the asset type.

**Comment by brandenrodgers** [comment]
Closing this because we are currently exploring potential solutions.
