### ISSUE TITLE
Add `hs config` command for making changes to the config

### ISSUE THREAD

**Issue by gcorne** [HubSpot/hubspot-cli#27]
In a fashion somewhat like `git config` and building on `hs init`, we should support making changes to the config via a `hs config` command.

**Comment by corymartin** [comment]
Via @TheWebTech 

> passing thought: would be cool if CLI had a command to quickly change default portal.
>
>I have like 6 portals in my config file and everytime I switch portals to make my life easier I just change that default instead of specifying --portal every time
>
> Bonus points would be to have a way to list the nicknames in the config file, so to make this change command easier to use.

**Comment by miketalley** [comment]
Two very good suggestions, I will add them when working on this!

**Comment by TheWebTech** [comment]
The bonus list nicknames feature should also visually denote the currently selected nickname. (just thought of that as I currently swap portals, and forgot which I was currently defaulted to.)
