### ISSUE TITLE
Document how deploy script could use personal access key

### ISSUE THREAD

**Issue by williamspiro** [HubSpot/hubspot-cli#270]
Document how the deploy script used in https://github.com/HubSpot/cms-theme-boilerplate and documented in https://developers.hubspot.com/docs/cms/guides/github-integration should use a personal CMS access key. 

This way, a deploy action could be tied to a user, with the name "GitHub Deploy" (or something like this).

**Comment by gcorne** [comment]
I think we also need to do https://github.com/HubSpot/hubspot-cms-tools/issues/257 as well as document using environment variables in general.

**Comment by brandenrodgers** [comment]
No longer a priority
