### ISSUE TITLE
Prettier Plugin

### ISSUE THREAD

**Issue by williamspiro** [HubSpot/hubspot-cli#279]
To support formatting in local text editors, we should build a prettier plugin. This could be done instead of https://github.com/HubSpot/hubspot-cms-vscode/issues/15

**Comment by gcorne** [comment]
https://github.com/justrhysism/prettier-plugin-nunjucks might be helpful as a starting point. It looks like it also is possible to use HTML comments to bypass prettier (see https://github.com/prettier/prettier/issues/5754#issuecomment-582230714).

**Comment by Nengeldir** [comment]
Hi everyone, is there an update on this issue? Or is there a workaround?

**Comment by chuckntaylor** [comment]
Also wondering if this project is still alive.

**Comment by anthmatic** [comment]
For anyone interested, we've got a beta version of the new Prettier Plugin for HubL up for you to try out: https://github.com/hubspot/prettier-plugin-hubl

**Comment by spanishgringo** [comment]
How do you get this to work with the prettier vs code extension?

**Comment by spanishgringo** [comment]
I have the .prettierrc file in my home directory. When I run the format command in VS Code for a file that is tagged as html-hubl I still see
**There is no formatter for 'html-hubl' files installed.**
with a button to **"Install formatter"**
