### ISSUE TITLE
Look into deployments for the github action

### ISSUE THREAD

**Issue by williamspiro** [HubSpot/hubspot-cli#303]
We should look into ways we could make our sample [GitHub deploy action](https://developers.hubspot.com/docs/cms/guides/github-integration) more transparent and powerful. 

Could we use [deployments](https://developer.github.com/v3/repos/deployments/) to display when the deploy action is still running and when it has succeeded?

**Comment by anthmatic** [comment]
It would be cool to set up a badge: https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/adding-a-workflow-status-badge#using-the-event-parameter

**Comment by gcorne** [comment]
@anthmatic this is complete now, correct?
