### ISSUE TITLE
Look into staging auto-deploy for deploy action

### ISSUE THREAD

**Issue by williamspiro** [HubSpot/hubspot-cli#304]
We should look into ways we could make our sample [GitHub deploy action](https://developers.hubspot.com/docs/cms/guides/github-integration) more transparent and powerful. 

We could experiment with auto-deploys to a "QA" portal when pushes are made to branches. 

<img width="518" alt="Screen Shot 2020-08-28 at 1 04 21 PM" src="https://user-images.githubusercontent.com/35824747/91593984-1f889180-e92f-11ea-9f71-6d5c7df23b73.png">

https://hubspotdev.slack.com/archives/CLJJXGTC0/p1598631094040400

**Comment by dennisedson** [comment]
@williamspiro, I would like to understand/ explore the transparency aspect of that statement.  
as for the deploy to QA, totally agree.

**Comment by anthmatic** [comment]
Added some info and an example of how to do this here https://github.com/HubSpot/hubspot-cms-deploy-action/blob/main/README.md#deploying-to-a-staging-account
