### ISSUE TITLE
Module label doesn't get written to meta.json

### ISSUE THREAD

**Issue by mike-blend** [HubSpot/hubspot-cli#395]
## Description and Context

Using the `create module` command prompts you to provide a label, which then doesn't get used.

**Version**: 2.2.0

### Steps to reproduce

`hs create module cta src/modules`
`? What should the module label be? Call to Action`

Generated meta.json;

```
{
  "css_assets": [],
  "external_js": [],
  "global": false,
  "help_text": "",
  "host_template_types": [
    "PAGE"
  ],
  "js_assets": [],
  "other_assets": [],
  "smart_type": "NOT_SMART",
  "tags": [],
  "is_available_for_new_content": false
}
```

## Expected behavior
`"label": "Call to Action"` should be written to meta.json

**Comment by anthmatic** [comment]
Thanks for reporting @mike-blend. This has been fixed and is available as a beta release now.
