### ISSUE TITLE
The hubspot cli tool should output the browser it tries to open

### ISSUE THREAD

**Issue by allan-simon** [HubSpot/hubspot-cli#444]
## Description and Context

When you use the CLI tool in a dockerized context or a on remote server , the cli tool has not directly access to the "main" browser of the user,  in that case, like for example what is done with heroku cli, it would be good if hubspot cli would also output the link in the console so that one can manually open it

**Comment by anthmatic** [comment]
@allan-simon is this in regards to the page that is opened when you run `hs auth`?

**Comment by allan-simon** [comment]
yes sorry I forgot to precise it was `hs auth` , right now I "hack" around it, by adding a console.log before the `open()`

**Comment by gcorne** [comment]
I am going to go ahead and take care of this.

**Comment by allan-simon** [comment]
thanks a lot !

**Comment by allan-simon** [comment]
awesome
