### ISSUE TITLE
Migrate "master" to "main"

### ISSUE THREAD

**Issue by TheWebTech** [HubSpot/hubspot-cli#522]
## Description and Context
Rename "master" branch to "main".
This update is fast and easy but I didn't want to just do - it as it could throw a wrench in someones work if they're in the middle of rushing to release something.

Basically we just need to click edit on the branches page https://github.com/HubSpot/hubspot-cli/branches

GitHub does the hard work for us. (migrating PRs, issues, informing devs that it was renamed and how to update local copies etc.)

https://github.com/github/renaming#rename-existing

**Comment by TanyaScales** [comment]
This is being handled internally right now and tracked via a ticket there - closing this out as a dupe
