### ISSUE TITLE
Handle no logs when running `hs logs <endpoint> --latest`

### ISSUE THREAD

**Issue by miketalley** [HubSpot/hubspot-cli#523]
## Description and Context
When running `hs logs <endpoint> --latest` when no logs are present, an error is encountered because the API returns a 404 if no logs are found. The response looks like...
```
{
  status: "error",
  message: "internal error",
  correlationId: <correlationId>
}
```

### Steps to reproduce
- Create a new function and do not execute it
- Run `hs logs <endpoint> --latest` referencing the new function endpoint

## Expected behavior
A message stating that no logs are found is displayed.

**Comment by gcorne** [comment]
What version of the CLI? I ask because I am pretty sure that I fixed this recently.
