### ISSUE TITLE
`node` should be a package dependency

### ISSUE THREAD

**Issue by m-roll** [HubSpot/hubspot-cli#586]
## Description and Context
When running `npm update -g @hubspot/cli@next` or `npm update -g @hubspot/cli@latest`, both `npm` and `hs` aren't discoverable via $PATH (seems binaries/symlinks get removed), if this is the only global package installed. This does not seem to happen when running `npm update @hubspot/cli`.

### Steps to reproduce
1. Run `npm update -g @hubspot/cli@latest`
2. `npm` will not be found by shell.

I *believe* the issue is that `node` needs to be a dependency of the CLI. When updating, it uses `package.json` to update the tree, sees that `node` isn't required, and then removes the cli. I think this only happens when all user packages do not have `node` as a dependency, it just so happens this is the only global user package I have. 

## Expected behavior
`npm` and `hs` remain in path

## Screenshots

<img width="447" alt="Screen Shot 2021-11-01 at 2 35 56 PM" src="https://user-images.githubusercontent.com/13841949/139723144-20d3adae-b634-4f74-bf32-08e279c34034.png">

## Who to Notify
@anthmatic

**Comment by miketalley** [comment]
Hey @m-roll thanks for posting this! I'm curious if this has to do with using `npm` instead of `yarn` for installing/updating the CLI. Have you tried using `yarn global add @hubspot/cli@next`?

**Comment by m-roll** [comment]
For some context, this issue (https://github.com/npm/cli/issues/2014#issuecomment-735944618) seems to indicate that this is not a bug. But I really am not too sure about how NPM works at the global level to say anything definitive here.

@miketalley Perhaps that is the case, although I would think that `npm` would work just as well with `package.json`. If `yarn` is required we should call that out in the readme, since we currently recommend installing via `npm`.

**Comment by miketalley** [comment]
Thanks for the reference @gcorne. I'm going to close this out. @m-roll be sure to comment if you are still seeing any issues.
