### ISSUE TITLE
hs fetch ignores --use-env

### ISSUE THREAD

**Issue by kaifresh** [HubSpot/hubspot-cli#620]
## Description and Context

Version: 3.0.9 

With the correct environment variables set, `hs fetch / --use-env` fails (asking for auth to be provided) while `hs list / --use-env` succeeds. 

It appears that [providing credentials via Environment Variables](https://developers.hubspot.com/docs/cms/developer-reference/local-development-cli#environment-variables) is not fully supported for the `hs fetch` command, but is for other `hs` commands.

### Steps to reproduce

Run the following commands in bash
```bash
HUBSPOT_PORTAL_ID=xxx HUBSPOT_API_KEY=xxx  hs list / --use-env && \
HUBSPOT_PORTAL_ID=xxx HUBSPOT_API_KEY=xxx  hs fetch / --use-env
```

## Expected behavior

Providing authentication via the environment and `--use-env` flag, I should be able to pull resources from my Design Manager

## Screenshots

N/A

## Who to Notify

@miketalley @brandenrodgers @gcorne  (just tagging you three as you're the authors of the `fetch.js` file. Not sure if there's someone more appropriate within hubspot?)

**Comment by anthmatic** [comment]
@kaifresh this issue was fixed recently but there hasn't been a new release of the CLI since then. We'll try to get a new version out shortly.

In the meantime, if this is blocking your workflow you can install the latest beta release of the cli `@hubspot/cli@next`

**Comment by kaifresh** [comment]
Thanks @anthmatic!! using it now
