### ISSUE TITLE
Add command to display user info

### ISSUE THREAD

**Issue by miketalley** [HubSpot/hubspot-cli#627]
## Description and Context
Create a command (`hs whoami` for example) that prints information about the current user and portal.

**Important**: Display the scopes available to the user for the associated portal. This will be useful for debugging.

**Comment by kcmaxwell** [comment]
Hello, I tried adding this command, but I ran into a problem displaying the available scopes.
They aren't being saved to the hubspot.config.yml, but from my testing the scopes are available in packages/cli-lib/personalAccessKey.js from the token generated by getAccessToken.
Is there some reason they are not being passed further and saved to the config?

**Comment by kcmaxwell** [comment]
@brandenrodgers Thanks for the advice! I was able to finish the command and created a pull request for it now.
