### ISSUE TITLE
Upgrade serverless functions to support Node 14.x

### ISSUE THREAD

**Issue by darkmavis1980** [HubSpot/hubspot-cli#628]
## Description and Context
At the moment when a user create a new serverless function via the CLI, the template sets uses `v12.x` of Node.js as a runtime, as this version is going out maintenance mode [officially in April](https://nodejs.org/en/about/releases/), would it better to upgrade the code to start to use `v14.x` instead?

### Steps to reproduce

Install the hubspot CLI commands then into a project run `hs create function test` to create the function, the files created will contain a `serverless.json` configuration, which has this line:

```json
"runtime": "nodejs12.x",
```

**Comment by darkmavis1980** [comment]
I did a bit more investigation, and apparently I get an error if I manually change the `serverless.json` configuration of my function to use `nodejs14.x`, so I presume is not yet supported in the CMS.
Does anybody has any idea if this is going to be supported anytime soon?

**Comment by gcorne** [comment]
Thanks for filing the request. This is something that we'll need to address via some changes on the backend for Serverless.

**Comment by darkmavis1980** [comment]
Yeah it's something that I figured once I manually set a different version and the hubspot designer refused to save it.
Feel free to close this issue if you prefer.

**Comment by darkmavis1980** [comment]
Node 14 is now supported, so I'm closing this one
