### ISSUE TITLE
Ability to add accounts through the CLI

### ISSUE THREAD

**Issue by arsduo** [HubSpot/hubspot-cli#657]
## Description and Context

Right now, there seems to be no way to add an account for local development through the CLI; you have to edit the `hubspot.config.yml` file manually. 

(Apologies if there is a way to do so, I've looked through all the available commands and all the documentation I can find, and don't see any open or closed issues that directly touch on this, other than #207, which was closed before `hs accounts` existed.)

### Steps to reproduce
A command like `hs accounts add` would prompt you appropriately to add another account to the `hubspot.config.yml` file

## Expected behavior
There is no such command; developers have to edit the file manually.

## Screenshots
n/a

Thank you very much!

**Comment by arsduo** [comment]
Ah, I just discovered that `hs auth` will add an account. The help description of `Configure authentication for a HubSpot account. Supported authentication protocols are oauth2 and personalaccesskey.` doesn't indicate it will also add accounts -- might be useful to add there, or add a note in the readme. 

Thanks for the useful CLI!

**Comment by brandenrodgers** [comment]
Thanks for the feedback @arsduo! This isn't the first time a command similar to `hs accounts add` has been proposed. It seems to be slightly more intuitive to people than `hs auth`. We'll look into it!
