### ISSUE TITLE
Error when trying to fetch files

### ISSUE THREAD

**Issue by ramonaguilera** [HubSpot/hubspot-cli#659]
I'm trying to fetch some directories from different accounts and I'm getting the same error on all of them.

This is the command: 'hs fetch Directory Directory'

'The request for "Directory/filename" in account XXXXXX failed due to a client error.'

Seems that it only happen with files and not directories.

I tried to reinstall Hubspot CLI, upgrade it to the last version (3.0.11), delete the account configuration, reset my IDE and computer... and nothing changes.
I also tried npm 8.5.0 (LTS) and npm 8.5.5 (lastest one) and still didn't work.

I'm using macOS Monterey version 12.2.1, chip Apple M1.

Please I need an answer as soon as posible

![image (8)](https://user-images.githubusercontent.com/23562574/160996038-b045adc3-e07d-43de-806b-485c83fddd2e.jpg)
.

**Comment by lucbenayoun31** [comment]
Same for me since this morning, this was working fine yesterday night
<img width="1460" alt="Capture d’écran 2022-03-31 à 09 06 01" src="https://user-images.githubusercontent.com/25349915/160997343-52aae080-bd4d-4da6-8d4a-c37175e4dd04.png">
.

**Comment by lucbenayoun31** [comment]
Same here since this morning, yesterday it was working fine. Uploading is working though.

![fetch-error](https://user-images.githubusercontent.com/25349915/161000713-5942694a-736e-4659-a017-768325670235.jpg)

Sorry @ramonaguilera had to remove my comment because it was containing my account reference, I updated my screenshot ;)

**Comment by ramonaguilera** [comment]
> Same here since this morning, yesterday it was working fine. Uploading is working though.
> 
> ![fetch-error](https://user-images.githubusercontent.com/25349915/161000713-5942694a-736e-4659-a017-768325670235.jpg)
> 
> Sorry @ramonaguilera had to remove my comment because it was containing my account reference, I updated my screenshot ;)

Don't worry! ;)

**Comment by mbaxter91288** [comment]
Same here getting the same error. Worked fine yesterday, today no dice.

Tried using `hs auth` to re-authenticate but no luck. Any ideas?

**Comment by dangvanthanh** [comment]
Same error with me on Windows 11

![hubspot](https://user-images.githubusercontent.com/2674850/161027965-3053c79a-055b-4075-bedc-82b8193bcdfd.png)

**Comment by ramonaguilera** [comment]
Apparently now it's working. Got solved in Hubspot official forum.

https://community.hubspot.com/t5/CMS-Development/Hubspot-CLI-Error-when-trying-to-fetch-files/m-p/605050/highlight/true#M28108
