### ISSUE TITLE
can't exec convert-fields command

### ISSUE THREAD

**Issue by 100handa** [HubSpot/hubspot-cli#774]
## Description and Context
I tried `hs convert-fields` command as [the document](https://developers.hubspot.com/docs/cms/building-blocks/modules/write-fields-using-javascript) says, but I've got a error message

> [ERROR] Unknown argument: convert-fields

CLI version is 4.1.3, Node.js version is v14.18.3

### Steps to reproduce
1. upgrade CLI with `npm install -g @hubspot/cli@latest`
2. confirm CLI version is 4.1.3 with `hs --version`
3. hit `hs convert-fields`

## Expected behavior
exec `hs convert-fields` command and converts `fields.js` files into `fields.output.json`

## Screenshots
<img width="415" alt="template-hubspot – button modulefields js 2022-12-02 at 4 42 19 PM" src="https://user-images.githubusercontent.com/112623261/205242261-86737e84-d829-4ec6-804c-fc799dba7e6a.png">

this is inside button.module of the [boilerplate](https://github.com/HubSpot/cms-theme-boilerplate) with `hs create website-theme`

**Comment by anthmatic** [comment]
It looks like the command in the docs is incorrect. The correct command is `hs cms convert-fields`.

Thank you for flagging this, we'll get that doc updated.
