### ISSUE TITLE
"appFunctions" prop is seems to be always needed when `hs project upload` exec

### ISSUE THREAD

**Issue by 100handa** [HubSpot/hubspot-cli#796]
### Context
I was trying deploy project only sever-less functions, without CRM cards.

### Description
1. `hs project upload` failed without "appFunctions" prop. And no concrete error messages received.
2. Added empty appFunction prop `"appFunctions": {}`
3. Tried `hs project upload` again
4. Success

### Steps to reproduce
Exec `hs project upload` without "appFunctions" prop.

## Expected behavior
Receive concrete error messages such as "appFunctions is required"

## Screenshots
![hs-cli-project](https://user-images.githubusercontent.com/112623261/209747717-bc457bbb-ee2f-4e8e-a88d-3935c4080dfb.gif)

**Comment by m-roll** [comment]
This is fixed now -- the server is validating against the uploaded JSON so now it should look something like
```
[ERROR] The post in account *** was bad. The JSON in the file '/app/app.functions/serverless.json' doesn't match the associated scheme. Correct and/or add values to all relevant fields and try again. 
- $.endpoints: is missing but it is required 
- $.appFunctions: is missing but it is required
```
