### ISSUE TITLE
Make sure fetching a folder with spaces in the name works as expected on Windows 10

### ISSUE THREAD

**Issue by gcorne** [HubSpot/hubspot-cli#85]

**Comment by corymartin** [comment]
![Screen Shot 2020-02-13 at 15 58 10](https://user-images.githubusercontent.com/687518/74477689-bc934980-4e79-11ea-91fa-b40d0b490cbb.png)

Works with root dir, nested dirs, and files with spaces.

**Comment by corymartin** [comment]
The issue is `npx`.  It seems to affect parameter parsing.

#### Correctly fetches remote dir `"/Custom modules"`
```
npm install -g @hubspot/cms-cli
hs fetch "Custom modules" test
```

#### Incorrectly fetches remote dir `"/Custom"`
```
npx hs fetch "Custom modules" test
```

**Comment by corymartin** [comment]
Maybe related https://github.com/npm/npx/issues/6

**Comment by corymartin** [comment]
`npx` on Windows certainly has trouble with string params. I made a simple module consisting of `console.log(process.argv)` and this was the output using `npx`

<img width="288" alt="Screen Shot 2020-02-19 at 18 14 17" src="https://user-images.githubusercontent.com/687518/74885840-886dcc00-5344-11ea-8e1a-22818658e1b4.png">

**Comment by corymartin** [comment]
https://github.com/npm/npx/issues/14

**Comment by mrinalpathak16** [comment]
try this -
https://stackoverflow.com/a/46871748/12581294

**Comment by miketalley** [comment]
Cannot repro this in windows. Seems to be working
![image](https://user-images.githubusercontent.com/6472448/116604317-f3794200-a8fb-11eb-96c1-e4b15b468404.png)
