### ISSUE TITLE
Fetch doesnt overwite existing modules  

### ISSUE THREAD

**Issue by adesignl** [HubSpot/hubspot-cli#9]
##Couple things i see could be better. 

(constructive criticism)

1. Help dialog needs to be updated to have all of the options listed. For a cli tool those are practically docs
2. Fetch should ask if you want to overwrite OR just assume since you are fetching and it will just pull the latest versions of your file (ALA git like).
3. It would be awesome if watch could watch remote as well. that way i dont have to come out of watch to update fields on a module if i'm already in watch.

![Screen Shot 2019-10-25 at 11 26 48 AM](https://user-images.githubusercontent.com/765914/67583834-6065b780-f71a-11e9-9ed7-f96b74cc99ff.png)

**Comment by corymartin** [comment]
Hi Chad.

> 1. Help dialog needs to be updated to have all of the options listed. For a cli tool those are practically docs

You can get detailed help for a specific command by using `--help` on it.  For example, the following will display all the options for `fetch`.

```shell
hs fetch --help
```
> 2. Fetch should ask if you want to overwrite OR just assume since you are fetching and it will just pull the latest versions of your file (ALA git like).

The default is `overwrite: false`.  I've thought about command prompts or help for certain actions (like path completion), so we are thinking about such things.  However, in the case of a command like `fetch` we'd likely want it to still be scriptable.  So relying an options is better for that.

> 3. It would be awesome if watch could watch remote as well. that way i don't have to come out of watch to update fields on a module if i'm already in watch.

🤔

**Comment by adesignl** [comment]
Thanks for the feed back. Insightful.

**Comment by brandenrodgers** [comment]
Closing in favor of #225

**Comment by ecupaio** [comment]
> Hi Chad.
> 
> > 1. Help dialog needs to be updated to have all of the options listed. For a cli tool those are practically docs
> 
> You can get detailed help for a specific command by using `--help` on it. For example, the following will display all the options for `fetch`.
> 
> ```shell
> hs fetch --help
> ```
> 
> > 2. Fetch should ask if you want to overwrite OR just assume since you are fetching and it will just pull the latest versions of your file (ALA git like).
> 
> The default is `overwrite: false`. I've thought about command prompts or help for certain actions (like path completion), so we are thinking about such things. However, in the case of a command like `fetch` we'd likely want it to still be scriptable. So relying an options is likely better for that.
> 
> > 3. It would be awesome if watch could watch remote as well. that way i don't have to come out of watch to update fields on a module if i'm already in watch.
> 
> 🤔

I was going insane trying to figure out why my fetch wasn't working. Is there a way to set overwrite true in the config.yml? It seems like not having overwrite will cause inconsistencies between local and prod, in fact it caused that issue for me when I used the UI to adjust a module. Also, is there a setting for watch that will sync file deletions? I removed a file locally while running the watch command but the prod instance won't recognize the deletion.
