### ISSUE TITLE
Deprecated Warnings while installing hubspot/cli package using npm.

### ISSUE THREAD

**Issue by sripada25** [HubSpot/hubspot-cli#938]
## Description and Context

Some of **hubpost/cli** (Latest version) package dependencies are deprecated.
  
### Steps to reproduce

1. Install nodejs @latest and npm 10 later.
2. Install hubspot/cli package using npm from command line (windows o.s). - npm install -g **@hubspot/cli**
## Expected behavior

Update the deprecated dependencies with any other latest npm working packages/dependencies can help the package to work as expected.

## Screenshots

![image](https://github.com/HubSpot/cms-theme-boilerplate/assets/140995816/3b213e79-1eaa-42cf-8de6-81ccb71a71b9)

**Comment by brandenrodgers** [comment]
Hi @sripada25, I believe this should be fixed now on the latest releases of the CLI. We had a dependency on the [deprecated request package](https://www.npmjs.com/package/request) which was causing all of these install warnings. We've since switched over to Axios.
