### ISSUE TITLE
5.1.0 looks for hubspot.config.yml despite --use-env flag.

### ISSUE THREAD

**Issue by matiasvad** [HubSpot/hubspot-cli#970]
Using @hubspot/cli@5.1.0 introduces a bug when used in automated deployment.
Automated deployments use the flag `--use-env`, rather than the config file `hubspot.config.yml`, as recommended her:
https://developers.hubspot.com/docs/cms/developer-reference/local-development-cli

However, the `upload` process fails, because it looks for the config file.

Set up environment variables, and use the `--use-env` flag. Run a `hs upload src dest --use-env` command. 

It will fail in the likes of:
```
2023-12-19T09:43:56.6387375Z A hubspot.config.yml file could not be found
2023-12-19T09:43:56.6536608Z [ERROR] Cannot destructure property 'auth' of 'getAccountConfig(...)' as it is null.
```

Can be fixed by using the @hubspot/cli@5.0.2 release.

@brandenrodgers cc'd since you committed the release.

**Comment by LukeTongue** [comment]
This is breaking the [hubspot-cms-deploy-action](https://github.com/HubSpot/hubspot-cms-deploy-action) too as this uses the latest version of the CLI. Is there any way around this?

**Comment by brandenrodgers** [comment]
Thank you for reporting this @matiasvad, we're looking into getting a fix out asap.

In the meantime, the workaround for this is to fork the HubSpot github action and pin the CLI version to 5.0.2 (rather than latest)

**Comment by brandenrodgers** [comment]
@matiasvad @LukeTongue we released a patch fix for this in v5.1.1. I'll hold off on closing this issue until you both can confirm that the github actions are working for you again.

**Comment by robbie-hypeanddexter** [comment]
@brandenrodgers I can confirm my deployments are successful now

**Comment by LukeTongue** [comment]
@brandenrodgers I too can confirm that deployments are all working now, thanks

**Comment by brandenrodgers** [comment]
Great, thanks for verifying!

**Comment by matiasvad** [comment]
I can also confirm that deployments work outside of the GitHub Action.

**Comment by torreyj** [comment]
Looks to be happening again as of today?

**Comment by Jeannot-MN** [comment]
It's currently happening today on my side too.

**Comment by brankko** [comment]
The same issue here. Just noticed it today.
