### ISSUE TITLE
Cant deploy github action - 'getAccountConfig(...)' as it is null error

### ISSUE THREAD

**Issue by torreyj** [HubSpot/hubspot-cli#982]
I'm getting these errors again. This is the same issue on this closed ticket from last month. https://github.com/HubSpot/hubspot-cli/issues/970
```
Error:  Cannot destructure property 'auth' of 'getAccountConfig(...)' as it is null.
Error: Process completed with exit code 1.
```
There's new comments on that closed ticket that explain what others are seeing as well.

**Comment by brandenrodgers** [comment]
Thank you for surfacing this, it should now be fixed in the latest CLI release (v5.1.2). We're planning to put some calories into catching these dependency issues so that we don't impact your workflow again.
